export const defaultNotifications = [{
  id: 'userAccessAlert',
  uiSort: 0,
  uiName: 'New User Access Request',
  uiDescription: 'Alert me when a new user requests permission to join my group.',
  uiSettingsTemplate: 'Alert me by {type} when {threshold} or more users request access to join my group.',
  smsTemplate: 'StatusEngine - We have identified __VALUE__ new user access request(s) in your group.',
  emailHtmlTemplate: '<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">'
    + '<html xmlns="http://www.w3.org/1999/xhtml" xmlns:v="urn:schemas-microsoft-com:vml" xmlns:o="urn:schemas-microsoft-com:office:office">'
    + '<head>'
    + '<!--[if (gte mso 9)|(IE)]>'
    + '  <xml>'
    + '    <o:OfficeDocumentSettings>'
    + '    <o:AllowPNG></o:AllowPNG>'
    + '    <o:PixelsPerInch>96</o:PixelsPerInch>'
    + '  </o:OfficeDocumentSettings>'
    + '</xml>'
    + '<![endif]-->'
    + '<meta http-equiv="Content-Type" content="text/html;charset=UTF-8">'
    + '<meta name="viewport" content="width=device-width, initial-scale=1"> <!-- So that mobile will display zoomed in -->'
    + '<meta http-equiv="X-UA-Compatible" content="IE=edge"> <!-- enable media queries for windows phone 8 -->'
    + '<meta name="format-detection" content="telephone=no"> <!-- disable auto telephone linking in iOS -->'
    + '<meta name="format-detection" content="date=no"> <!-- disable auto date linking in iOS -->'
    + '<meta name="format-detection" content="address=no"> <!-- disable auto address linking in iOS -->'
    + '<meta name="format-detection" content="email=no"> <!-- disable auto email linking in iOS -->'
    + '<title>New User Access Request</title>'
    + '<style type="text/css">'
    + '/*Basics*/'
    + 'body {margin:0px!important;padding:0px!important;display:block!important;min-width:100%!important;width:100%!important;-webkit-text-size-adjust:none;}'
    + 'table {border-spacing:0;mso-table-lspace:0pt;mso-table-rspace:0pt;}'
    + 'table td {border-collapse:collapse;mso-line-height-rule:exactly;}'
    + 'td img {-ms-interpolation-mode:bicubic;width:auto;max-width:auto;height:auto;margin:auto;display:block!important;border:0px;}'
    + 'td p {margin:0;padding:0;}'
    + 'td div {margin:0;padding:0;}'
    + 'td a {text-decoration:none;color:#005ea2;}'
    + '/*Outlook*/'
    + '.ExternalClass {width:100%;}'
    + '.ExternalClass,.ExternalClass p,.ExternalClass span,.ExternalClass font,.ExternalClass td,.ExternalClass div {line-height:inherit;}'
    + '.ReadMsgBody {width:100%;background-color:#ffffff;}'
    + '/* iOS BLUE LINKS */'
    + 'a[x-apple-data-detectors] {color:inherit!important;text-decoration:none!important;font-size:inherit!important;font-family:inherit!important;font-weight:inherit!important;line-height:inherit!important;}'
    + '/*Gmail blue links*/'
    + 'u + #body a {color:inherit;text-decoration:none;font-size:inherit;font-family:inherit;font-weight:inherit;line-height:inherit;}'
    + '/*Buttons fix*/'
    + '.undoreset a, .undoreset a:hover {text-decoration:none!important;}'
    + '.yshortcuts a {border-bottom:none!important;}'
    + '.ios-footer a {color:#aaaaaa!important;text-decoration:none;}'
    + '/*Responsive*/'
    + '@media screen and (max-width:799px) {'
    + '  table.row {width:100%!important;max-width:100%!important;}'
    + '  td.row {width:100%!important;max-width:100%!important;}'
    + '  .img-responsive img {width:100%!important;max-width:100%!important;height:auto!important;margin:auto;}'
    + '  .center-float {float:none!important;margin:auto!important;}'
    + '  .center-text{text-align:center!important;}'
    + '  .container-padding {width:100%!important;padding-left:15px!important;padding-right:15px!important;}'
    + '  .container-padding10 {width:100%!important;padding-left:10px!important;padding-right:10px!important;}'
    + '  .hide-mobile {display:none!important;}'
    + '  .menu-container {text-align:center!important;}'
    + '  .autoheight {height:auto!important;}'
    + '  .m-padding-10 {margin:10px 0!important;}'
    + '  .m-padding-15 {margin:15px 0!important;}'
    + '  .m-padding-20 {margin:20px 0!important;}'
    + '  .m-padding-30 {margin:30px 0!important;}'
    + '  .m-padding-40 {margin:40px 0!important;}'
    + '  .m-padding-50 {margin:50px 0!important;}'
    + '  .m-padding-60 {margin:60px 0!important;}'
    + '  .m-padding-top10 {margin:30px 0 0 0!important;}'
    + '  .m-padding-top15 {margin:15px 0 0 0!important;}'
    + '  .m-padding-top20 {margin:20px 0 0 0!important;}'
    + '  .m-padding-top30 {margin:30px 0 0 0!important;}'
    + '  .m-padding-top40 {margin:40px 0 0 0!important;}'
    + '  .m-padding-top50 {margin:50px 0 0 0!important;}'
    + '  .m-padding-top60 {margin:60px 0 0 0!important;}'
    + '  .m-height10 {font-size:10px!important;line-height:10px!important;height:10px!important;}'
    + '  .m-height15 {font-size:15px!important;line-height:15px!important;height:15px!important;}'
    + '  .m-height20 {font-size:20px!important;line-height:20px!important;height:20px!important;}'
    + '  .m-height25 {font-size:25px!important;line-height:25px!important;height:25px!important;}'
    + '  .m-height30 {font-size:30px!important;line-height:30px!important;height:30px!important;}'
    + '  .rwd-on-mobile {display:inline-block!important;padding:5px;}'
    + '  .center-on-mobile {text-align:center!important;}'
    + '}'
    + '</style>'
    + ''
    + '<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Public Sans:100,200,300,400,500,600,700,800,900,100italic,200italic,300italic,400italic,500italic,600italic,700italic,800italic,900italic"></head>'
    + '<body style="margin-top:0;margin-bottom:0;padding-top:0;padding-bottom:0;width:100%;-webkit-text-size-adjust:100%;-ms-text-size-adjust:100%;" bgcolor="#f0f0f0">'
    + '<span class="preheader-text" style="color:transparent;height:0;max-height:0;max-width:0;opacity:0;overflow:hidden;visibility:hidden;width:0;display:none;mso-hide:all;">We have identified new user access requests that require your attention.</span>'
    + ''
    + '<table border="0" align="center" cellpadding="0" cellspacing="0" width="100%" style="width:100%;max-width:100%;">'
    + '  <tbody><tr><!-- Outer Table -->'
    + '    <td align="center" bgcolor="#F4F4F4">'
    + '                        <table border="0" align="center" cellpadding="0" cellspacing="0" role="presentation" width="100%" style="width:100%;max-width:100%;">'
    + '  <!-- header-1 -->'
    + '  <tbody><tr>'
    + '    <td align="center" bgcolor="#3a4758" class="container-padding">'
    + '<!-- Content -->'
    + '<table border="0" align="center" cellpadding="0" cellspacing="0" role="presentation" class="row" width="640" style="width:640px;max-width:640px;">'
    + '  <tbody><tr>'
    + '    <td height="40" style="font-size:40px;line-height:40px;"> </td>'
    + '  </tr>'
    + '  <tr>'
    + '    <td align="center">'
    + '      <!-- Logo & Webview -->'
    + '      <table border="0" align="center" cellpadding="0" cellspacing="0" role="presentation" width="100%" style="width:100%;max-width:100%;">'
    + '        <tbody><tr>'
    + '          <td align="center" class="container-padding">'
    + '      <!--[if (gte mso 9)|(IE)]><table border="0" cellpadding="0" cellspacing="0" dir="rtl"><tr><td><![endif]-->'
    + '      <!-- Column -->'
    + '      <table border="0" align="right" cellpadding="0" cellspacing="0" role="presentation" class="row" width="280" style="width:280px;max-width:280px;">'
    + '        <tbody><tr>'
    + '          <td class="center-text" align="right" height="32" style="height:32px;">'
    + '            <a href="#" style="font-family:\'Public Sans\', Arial, Helvetica, sans-serif;font-size:12px;line-height:16px;font-style:italic;font-weight:400;color:#dcddde;text-decoration:none;letter-spacing:0px;">View this email in your browser</a>'
    + '          </td>'
    + '        </tr>'
    + '      </tbody></table>'
    + '      <!-- Column -->'
    + '      <!--[if (gte mso 9)|(IE)]></td><td><![endif]-->'
    + '      <!-- Gap -->'
    + '      <table border="0" align="right" cellpadding="0" cellspacing="0" role="presentation" class="row" width="20" style="width:20px;max-width:20px;">'
    + '        <tbody><tr>'
    + '          <td height="20" style="font-size:20px;line-height:20px;"> </td>'
    + '        </tr>'
    + '      </tbody></table>'
    + '      <!-- Gap -->'
    + '      <!--[if (gte mso 9)|(IE)]></td><td><![endif]-->'
    + '      <!-- Column -->'
    + '      <table border="0" align="right" cellpadding="0" cellspacing="0" role="presentation" class="row" width="340" style="width:340px;max-width:340px;">'
    + '        <tbody><tr>'
    + '          <td align="left" class="center-text">'
    + '            <img style="width:211px;border:0px;display:inline!important;" src="__IMAGE_URL__/logo.png" width="211" border="0" alt="logo">'
    + '          </td>'
    + '        </tr>'
    + '      </tbody></table>'
    + '      <!-- Column -->'
    + '      <!--[if (gte mso 9)|(IE)]></td></tr></table><![endif]-->'
    + '          </td>'
    + '        </tr>'
    + '      </tbody></table>'
    + '      <!-- Logo & Webview -->'
    + '    </td>'
    + '  </tr>'
    + '  <tr>'
    + '    <td height="80" style="font-size:40px;line-height:80px;"> </td>'
    + '  </tr>'
    + '  <tr>'
    + '    <td align="center" class="center-text">'
    + '      <img style="width:218px;border:0px;display:inline!important;" src="__IMAGE_URL__/hand-lock.png" width="218" border="0" alt="intro">'
    + '    </td>'
    + '  </tr>'
    + '  <tr>'
    + '    <td height="80" style="font-size:40px;line-height:80px;"> </td>'
    + '  </tr>'
    + '  <tr>'
    + '    <td class="center-text" align="center" style="font-family:\'Public Sans\', Arial, Helvetica, sans-serif;font-size:36px;line-height:40px;font-weight:700;font-style:normal;color:rgb(255, 255, 255);text-decoration:none;letter-spacing:0.75px;">'
    + '        <singleline>'
    + '          <div style="margin: 0px; padding: 0px;"><p style="margin: 0px; padding: 0px;">New User Access Request</p><p style="margin: 0px; padding: 0px;">'
    + '          </p></div>'
    + '        </singleline>'
    + '    </td>'
    + '  </tr>'
    + '  <tr>'
    + '    <td height="20" style="font-size:20px;line-height:20px;"> </td>'
    + '  </tr>'
    + '  <tr>'
    + '    <td class="center-text" align="center" style="font-family:\'Public Sans\', Arial, Helvetica, sans-serif;font-size:22px;line-height:29px;font-weight:300;font-style:normal;color:rgb(255, 255, 255);text-decoration:none;letter-spacing:0px;">'
    + '        <singleline>'
    + '          <div style="margin: 0px; padding: 0px;"><p style="margin: 0px; padding: 0px;">We have identified <strong style="color:#7efbe1;">__VALUE__ new user access request(s) </strong>that require your attention.</p><p style="margin: 0px; padding: 0px;">'
    + '          </p></div>'
    + '        </singleline>'
    + '    </td>'
    + '  </tr>'
    + '  <tr>'
    + '    <td height="40" style="font-size:40px;line-height:40px;"> </td>'
    + '  </tr>'
    + '  <tr>'
    + '    <td align="center">'
    + '      <!-- Header Button -->'
    + '      <table border="0" cellspacing="0" cellpadding="0" role="presentation" align="center" class="center-float">'
    + '        <tbody><tr>'
    + '          <td align="center" bgcolor="transparent" style="border-radius:5px; border: 2px solid white;">'
    + '      <!--[if (gte mso 9)|(IE)]>'
    + '        <table border="0" cellpadding="0" cellspacing="0" align="center">'
    + '          <tr>'
    + '            <td align="center" width="50"></td>'
    + '            <td align="center" height="50" style="height:50px;">'
    + '            <![endif]-->'
    + '              <singleline>'
    + '                <a href="__LINK__" target="_blank" style="font-family:\'Public Sans\', Arial, Helvetica, sans-serif;font-size:22px;line-height:29px;font-weight:500;font-style:normal;color:rgb(255, 255, 255);text-decoration:none;letter-spacing:0px;letter-spacing:0px;padding:20px 80px 20px 80px;display:inline-block;"><span>Review Now</span></a>'
    + '              </singleline>'
    + '            <!--[if (gte mso 9)|(IE)]>'
    + '            </td>'
    + '            <td align="center" width="50"></td>'
    + '          </tr>'
    + '        </table>'
    + '      <![endif]-->'
    + '          </td>'
    + '        </tr>'
    + '      </tbody></table>'
    + '      <!-- Header Button -->'
    + '    </td>'
    + '  </tr>'
    + '  <tr>'
    + '    <td height="100" style="font-size:40px;line-height:60px;"> </td>'
    + '  </tr>'
    + '</tbody></table>'
    + '<!-- Content -->'
    + '    </td>'
    + '  </tr>'
    + '</tbody></table><table border="0" align="center" cellpadding="0" cellspacing="0" role="presentation" width="100%" style="width:100%;max-width:100%;">'
    + '  <!-- Footer -->'
    + '  <tbody><tr>'
    + '    <td align="center" bgcolor="#f0f0f0" class="container-padding">'
    + '<!-- Content -->'
    + '<table border="0" align="center" cellpadding="0" cellspacing="0" role="presentation" class="row" width="640" style="width:640px;max-width:640px;">'
    + '  <tbody><tr>'
    + '    <td height="50" style="font-size:50px;line-height:50px;"> </td>'
    + '  </tr>'
    + ''
    + ''
    + '  <tr style="">'
    + '    <td class="center-text" align="center" style="font-family:\'Public Sans\', Arial, Helvetica, sans-serif;font-size:14px;line-height:26px;font-weight:300;font-style:normal;color:rgb(110, 110, 110);text-decoration:none;letter-spacing:0px;">'
    + '      <multiline>'
    + '        <div style="margin: 0px; padding: 0px;"><p style="margin: 0px; padding: 0px;">This email was sent because you are a registered member of StatusEngine and have opted in to receive email communications. If you wish to change these settings, you can adjust your <a href="#" target="_blank" style="text-decoration: none;">email preferences</a> any time.</p><p style="margin: 0px; padding: 0px;"><br></p><p style="margin: 0px; padding: 0px;">Please send any feedback or bug reports to  <a href="mailto:support@mystatusengine.gov" target="_blank" style="text-decoration: none;">support@mystatusengine.gov</a></p><p style="margin: 0px; padding: 0px;">'
    + '        </p></div>'
    + '      </multiline>'
    + '    </td>'
    + '  </tr>'
    + '  <tr>'
    + '    <td height="30" style="font-size:30px;line-height:30px;"> </td>'
    + '  </tr>'
    + '  <tr>'
    + '    <td height="50" style="font-size:50px;line-height:50px;"> </td>'
    + '  </tr>'
    + '</tbody></table>'
    + '<!-- Content -->'
    + '    </td>'
    + '  </tr>'
    + '</tbody></table></td>'
    + '  </tr><!-- Outer-Table -->'
    + '</tbody></table>'
    + '</body>'
    + '</html>',
  emailTextTemplate: 'We have identified __VALUE__ new user access request(s) in your group. __LINK__',
  dashboardUuid: '',
  defaultMaxDailyCount: 0,
  defaultThreshold: 1,
  defaultMinTimeBetweenAlerts: 180,
}, {
  id: 'medicalAttentionAlert',
  uiSort: 1,
  uiName: 'Individual Needs Medical Attention',
  uiDescription: 'Alert me when an individual in my group needs attention from medical staff.',
  uiSettingsTemplate: 'Alert me by {type} when {threshold} or more individuals require medical attention.',
  smsTemplate: 'StatusEngine - We have identified __VALUE__ new individual(s) that have require attention from medical staff.',
  emailHtmlTemplate: '<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">'
    + '<html xmlns="http://www.w3.org/1999/xhtml" xmlns:v="urn:schemas-microsoft-com:vml" xmlns:o="urn:schemas-microsoft-com:office:office">'
    + '<head>'
    + '<!--[if (gte mso 9)|(IE)]>'
    + '  <xml>'
    + '    <o:OfficeDocumentSettings>'
    + '    <o:AllowPNG></o:AllowPNG>'
    + '    <o:PixelsPerInch>96</o:PixelsPerInch>'
    + '  </o:OfficeDocumentSettings>'
    + '</xml>'
    + '<![endif]-->'
    + '<meta http-equiv="Content-Type" content="text/html;charset=UTF-8">'
    + '<meta name="viewport" content="width=device-width, initial-scale=1"> <!-- So that mobile will display zoomed in -->'
    + '<meta http-equiv="X-UA-Compatible" content="IE=edge"> <!-- enable media queries for windows phone 8 -->'
    + '<meta name="format-detection" content="telephone=no"> <!-- disable auto telephone linking in iOS -->'
    + '<meta name="format-detection" content="date=no"> <!-- disable auto date linking in iOS -->'
    + '<meta name="format-detection" content="address=no"> <!-- disable auto address linking in iOS -->'
    + '<meta name="format-detection" content="email=no"> <!-- disable auto email linking in iOS -->'
    + '<title>Individual Needs Medical Attention</title>'
    + '<style type="text/css">'
    + '/*Basics*/'
    + 'body {margin:0px!important;padding:0px!important;display:block!important;min-width:100%!important;width:100%!important;-webkit-text-size-adjust:none;}'
    + 'table {border-spacing:0;mso-table-lspace:0pt;mso-table-rspace:0pt;}'
    + 'table td {border-collapse:collapse;mso-line-height-rule:exactly;}'
    + 'td img {-ms-interpolation-mode:bicubic;width:auto;max-width:auto;height:auto;margin:auto;display:block!important;border:0px;}'
    + 'td p {margin:0;padding:0;}'
    + 'td div {margin:0;padding:0;}'
    + 'td a {text-decoration:none;color:#005ea2;}'
    + '/*Outlook*/'
    + '.ExternalClass {width:100%;}'
    + '.ExternalClass,.ExternalClass p,.ExternalClass span,.ExternalClass font,.ExternalClass td,.ExternalClass div {line-height:inherit;}'
    + '.ReadMsgBody {width:100%;background-color:#ffffff;}'
    + '/* iOS BLUE LINKS */'
    + 'a[x-apple-data-detectors] {color:inherit!important;text-decoration:none!important;font-size:inherit!important;font-family:inherit!important;font-weight:inherit!important;line-height:inherit!important;}'
    + '/*Gmail blue links*/'
    + 'u + #body a {color:inherit;text-decoration:none;font-size:inherit;font-family:inherit;font-weight:inherit;line-height:inherit;}'
    + '/*Buttons fix*/'
    + '.undoreset a, .undoreset a:hover {text-decoration:none!important;}'
    + '.yshortcuts a {border-bottom:none!important;}'
    + '.ios-footer a {color:#aaaaaa!important;text-decoration:none;}'
    + '/*Responsive*/'
    + '@media screen and (max-width:799px) {'
    + '  table.row {width:100%!important;max-width:100%!important;}'
    + '  td.row {width:100%!important;max-width:100%!important;}'
    + '  .img-responsive img {width:100%!important;max-width:100%!important;height:auto!important;margin:auto;}'
    + '  .center-float {float:none!important;margin:auto!important;}'
    + '  .center-text{text-align:center!important;}'
    + '  .container-padding {width:100%!important;padding-left:15px!important;padding-right:15px!important;}'
    + '  .container-padding10 {width:100%!important;padding-left:10px!important;padding-right:10px!important;}'
    + '  .hide-mobile {display:none!important;}'
    + '  .menu-container {text-align:center!important;}'
    + '  .autoheight {height:auto!important;}'
    + '  .m-padding-10 {margin:10px 0!important;}'
    + '  .m-padding-15 {margin:15px 0!important;}'
    + '  .m-padding-20 {margin:20px 0!important;}'
    + '  .m-padding-30 {margin:30px 0!important;}'
    + '  .m-padding-40 {margin:40px 0!important;}'
    + '  .m-padding-50 {margin:50px 0!important;}'
    + '  .m-padding-60 {margin:60px 0!important;}'
    + '  .m-padding-top10 {margin:30px 0 0 0!important;}'
    + '  .m-padding-top15 {margin:15px 0 0 0!important;}'
    + '  .m-padding-top20 {margin:20px 0 0 0!important;}'
    + '  .m-padding-top30 {margin:30px 0 0 0!important;}'
    + '  .m-padding-top40 {margin:40px 0 0 0!important;}'
    + '  .m-padding-top50 {margin:50px 0 0 0!important;}'
    + '  .m-padding-top60 {margin:60px 0 0 0!important;}'
    + '  .m-height10 {font-size:10px!important;line-height:10px!important;height:10px!important;}'
    + '  .m-height15 {font-size:15px!important;line-height:15px!important;height:15px!important;}'
    + '  .m-height20 {font-size:20px!important;line-height:20px!important;height:20px!important;}'
    + '  .m-height25 {font-size:25px!important;line-height:25px!important;height:25px!important;}'
    + '  .m-height30 {font-size:30px!important;line-height:30px!important;height:30px!important;}'
    + '  .rwd-on-mobile {display:inline-block!important;padding:5px;}'
    + '  .center-on-mobile {text-align:center!important;}'
    + '}'
    + '</style>'
    + ''
    + '<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Public Sans:100,200,300,400,500,600,700,800,900,100italic,200italic,300italic,400italic,500italic,600italic,700italic,800italic,900italic"></head>'
    + '<body style="margin-top:0;margin-bottom:0;padding-top:0;padding-bottom:0;width:100%;-webkit-text-size-adjust:100%;-ms-text-size-adjust:100%;" bgcolor="#f0f0f0">'
    + '<span class="preheader-text" style="color:transparent;height:0;max-height:0;max-width:0;opacity:0;overflow:hidden;visibility:hidden;width:0;display:none;mso-hide:all;">We have identified individuals that require attention from medical staff.</span>'
    + ''
    + '<table border="0" align="center" cellpadding="0" cellspacing="0" width="100%" style="width:100%;max-width:100%;">'
    + '  <tbody><tr><!-- Outer Table -->'
    + '    <td align="center" bgcolor="#F4F4F4">'
    + '                        <table border="0" align="center" cellpadding="0" cellspacing="0" role="presentation" width="100%" style="width:100%;max-width:100%;">'
    + '  <!-- Header -->'
    + '  <tbody><tr>'
    + '    <td align="center" bgcolor="#3a4758" class="container-padding">'
    + '<!-- Content -->'
    + '<table border="0" align="center" cellpadding="0" cellspacing="0" role="presentation" class="row" width="640" style="width:640px;max-width:640px;">'
    + '  <tbody><tr>'
    + '    <td height="40" style="font-size:40px;line-height:40px;"> </td>'
    + '  </tr>'
    + '  <tr>'
    + '    <td align="center">'
    + '      <!-- Logo & Webview -->'
    + '      <table border="0" align="center" cellpadding="0" cellspacing="0" role="presentation" width="100%" style="width:100%;max-width:100%;">'
    + '        <tbody><tr>'
    + '          <td align="center" class="container-padding">'
    + '      <!--[if (gte mso 9)|(IE)]><table border="0" cellpadding="0" cellspacing="0" dir="rtl"><tr><td><![endif]-->'
    + '      <!-- Column -->'
    + '      <table border="0" align="right" cellpadding="0" cellspacing="0" role="presentation" class="row" width="280" style="width:280px;max-width:280px;">'
    + '        <tbody><tr>'
    + '          <td class="center-text" align="right" height="32" style="height:32px;">'
    + '            <a href="#" style="font-family:\'Public Sans\', Arial, Helvetica, sans-serif;font-size:12px;line-height:16px;font-style:italic;font-weight:400;color:#dcddde;text-decoration:none;letter-spacing:0px;">View this email in your browser</a>'
    + '          </td>'
    + '        </tr>'
    + '      </tbody></table>'
    + '      <!-- Column -->'
    + '      <!--[if (gte mso 9)|(IE)]></td><td><![endif]-->'
    + '      <!-- Gap -->'
    + '      <table border="0" align="right" cellpadding="0" cellspacing="0" role="presentation" class="row" width="20" style="width:20px;max-width:20px;">'
    + '        <tbody><tr>'
    + '          <td height="20" style="font-size:20px;line-height:20px;"> </td>'
    + '        </tr>'
    + '      </tbody></table>'
    + '      <!-- Gap -->'
    + '      <!--[if (gte mso 9)|(IE)]></td><td><![endif]-->'
    + '      <!-- Column -->'
    + '      <table border="0" align="right" cellpadding="0" cellspacing="0" role="presentation" class="row" width="340" style="width:340px;max-width:340px;">'
    + '        <tbody><tr>'
    + '          <td align="left" class="center-text">'
    + '            <img style="width:211px;border:0px;display:inline!important;" src="__IMAGE_URL__/logo.png" width="211" border="0" alt="logo">'
    + '          </td>'
    + '        </tr>'
    + '      </tbody></table>'
    + '      <!-- Column -->'
    + '      <!--[if (gte mso 9)|(IE)]></td></tr></table><![endif]-->'
    + '          </td>'
    + '        </tr>'
    + '      </tbody></table>'
    + '      <!-- Logo & Webview -->'
    + '    </td>'
    + '  </tr>'
    + '  <tr>'
    + '    <td height="80" style="font-size:40px;line-height:80px;"> </td>'
    + '  </tr>'
    + '  <tr>'
    + '    <td align="center" class="center-text">'
    + '      <img style="width:218px;border:0px;display:inline!important;" src="__IMAGE_URL__/medical-briefcase.png" width="218" border="0" alt="intro">'
    + '    </td>'
    + '  </tr>'
    + '  <tr>'
    + '    <td height="80" style="font-size:40px;line-height:80px;"> </td>'
    + '  </tr>'
    + '  <tr>'
    + '    <td class="center-text" align="center" style="font-family:\'Public Sans\', Arial, Helvetica, sans-serif;font-size:36px;line-height:40px;font-weight:700;font-style:normal;color:rgb(255, 255, 255);text-decoration:none;letter-spacing:0.75px;">'
    + '        <singleline>'
    + '          <div style="margin: 0px; padding: 0px;"><p style="margin: 0px; padding: 0px;">Individual Needs Medical Attention</p><p style="margin: 0px; padding: 0px;">'
    + '          </p></div>'
    + '        </singleline>'
    + '    </td>'
    + '  </tr>'
    + '  <tr>'
    + '    <td height="20" style="font-size:20px;line-height:20px;"> </td>'
    + '  </tr>'
    + '  <tr>'
    + '    <td class="center-text" align="center" style="font-family:\'Public Sans\', Arial, Helvetica, sans-serif;font-size:22px;line-height:29px;font-weight:300;font-style:normal;color:rgb(255, 255, 255);text-decoration:none;letter-spacing:0px;">'
    + '        <singleline>'
    + '          <div style="margin: 0px; padding: 0px;"><p style="margin: 0px; padding: 0px;">We have identified <strong style="color:#7efbe1;">__VALUE__ new individual(s) </strong>that require attention from medical staff.</p><p style="margin: 0px; padding: 0px;">'
    + '          </p></div>'
    + '        </singleline>'
    + '    </td>'
    + '  </tr>'
    + '  <tr>'
    + '    <td height="40" style="font-size:40px;line-height:40px;"> </td>'
    + '  </tr>'
    + '  <tr>'
    + '    <td align="center">'
    + '      <!-- Header Button -->'
    + '      <table border="0" cellspacing="0" cellpadding="0" role="presentation" align="center" class="center-float">'
    + '        <tbody><tr>'
    + '          <td align="center" bgcolor="transparent" style="border-radius:5px; border: 2px solid white;">'
    + '      <!--[if (gte mso 9)|(IE)]>'
    + '        <table border="0" cellpadding="0" cellspacing="0" align="center">'
    + '          <tr>'
    + '            <td align="center" width="50"></td>'
    + '            <td align="center" height="50" style="height:50px;">'
    + '            <![endif]-->'
    + '              <singleline>'
    + '                <a href="__LINK__" target="_blank" style="font-family:\'Public Sans\', Arial, Helvetica, sans-serif;font-size:22px;line-height:29px;font-weight:500;font-style:normal;color:rgb(255, 255, 255);text-decoration:none;letter-spacing:0px;letter-spacing:0px;padding:20px 80px 20px 80px;display:inline-block;"><span>Review Now</span></a>'
    + '              </singleline>'
    + '            <!--[if (gte mso 9)|(IE)]>'
    + '            </td>'
    + '            <td align="center" width="50"></td>'
    + '          </tr>'
    + '        </table>'
    + '      <![endif]-->'
    + '          </td>'
    + '        </tr>'
    + '      </tbody></table>'
    + '      <!-- Header Button -->'
    + '    </td>'
    + '  </tr>'
    + '  <tr>'
    + '    <td height="100" style="font-size:40px;line-height:60px;"> </td>'
    + '  </tr>'
    + '</tbody></table>'
    + '<!-- Content -->'
    + '    </td>'
    + '  </tr>'
    + '</tbody></table><table border="0" align="center" cellpadding="0" cellspacing="0" role="presentation" width="100%" style="width:100%;max-width:100%;">'
    + '  <!-- Footer -->'
    + '  <tbody><tr>'
    + '    <td align="center" bgcolor="#f0f0f0" class="container-padding">'
    + '<!-- Content -->'
    + '<table border="0" align="center" cellpadding="0" cellspacing="0" role="presentation" class="row" width="640" style="width:640px;max-width:640px;">'
    + '  <tbody><tr>'
    + '    <td height="50" style="font-size:50px;line-height:50px;"> </td>'
    + '  </tr>'
    + ''
    + ''
    + '  <tr style="">'
    + '    <td class="center-text" align="center" style="font-family:\'Public Sans\', Arial, Helvetica, sans-serif;font-size:14px;line-height:26px;font-weight:300;font-style:normal;color:rgb(110, 110, 110);text-decoration:none;letter-spacing:0px;">'
    + '      <multiline>'
    + '        <div style="margin: 0px; padding: 0px;"><p style="margin: 0px; padding: 0px;">This email was sent because you are a registered member of StatusEngine and have opted in to receive email communications. If you wish to change these settings, you can adjust your <a href="#" target="_blank" style="text-decoration: none;">email preferences</a> any time.</p><p style="margin: 0px; padding: 0px;"><br></p><p style="margin: 0px; padding: 0px;">Please send any feedback or bug reports to  <a href="mailto:support@mystatusengine.gov" target="_blank" style="text-decoration: none;">support@mystatusengine.gov</a></p><p style="margin: 0px; padding: 0px;">'
    + '        </p></div>'
    + '      </multiline>'
    + '    </td>'
    + '  </tr>'
    + '  <tr>'
    + '    <td height="30" style="font-size:30px;line-height:30px;"> </td>'
    + '  </tr>'
    + '  <tr>'
    + '    <td height="50" style="font-size:50px;line-height:50px;"> </td>'
    + '  </tr>'
    + '</tbody></table>'
    + '<!-- Content -->'
    + '    </td>'
    + '  </tr>'
    + '</tbody></table></td>'
    + '  </tr><!-- Outer-Table -->'
    + '</tbody></table>'
    + '</body>'
    + '</html>',
  emailTextTemplate: 'We have identified __VALUE__ new individual(s) that require attention from medical staff. __LINK__',
  dashboardUuid: '',
  defaultMaxDailyCount: 0,
  defaultThreshold: 1,
  defaultMinTimeBetweenAlerts: 60,
}, {
  id: 'speakToSomeoneAlert',
  uiSort: 2,
  uiName: 'Individual Needs to Speak with Someone',
  uiDescription: 'Alert me when an individual in my group requests to speak with someone.',
  uiSettingsTemplate: 'Alert me by {type} when {threshold} or more individuals request to speak with someone.',
  smsTemplate: 'StatusEngine - We have identified __VALUE__ individual(s) within your group that have requested to speak with someone.',
  emailHtmlTemplate: '<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">'
    + '<html xmlns="http://www.w3.org/1999/xhtml" xmlns:v="urn:schemas-microsoft-com:vml" xmlns:o="urn:schemas-microsoft-com:office:office">'
    + '<head>'
    + '<!--[if (gte mso 9)|(IE)]>'
    + '  <xml>'
    + '    <o:OfficeDocumentSettings>'
    + '    <o:AllowPNG></o:AllowPNG>'
    + '    <o:PixelsPerInch>96</o:PixelsPerInch>'
    + '  </o:OfficeDocumentSettings>'
    + '</xml>'
    + '<![endif]-->'
    + '<meta http-equiv="Content-Type" content="text/html;charset=UTF-8">'
    + '<meta name="viewport" content="width=device-width, initial-scale=1"> <!-- So that mobile will display zoomed in -->'
    + '<meta http-equiv="X-UA-Compatible" content="IE=edge"> <!-- enable media queries for windows phone 8 -->'
    + '<meta name="format-detection" content="telephone=no"> <!-- disable auto telephone linking in iOS -->'
    + '<meta name="format-detection" content="date=no"> <!-- disable auto date linking in iOS -->'
    + '<meta name="format-detection" content="address=no"> <!-- disable auto address linking in iOS -->'
    + '<meta name="format-detection" content="email=no"> <!-- disable auto email linking in iOS -->'
    + '<title>Individual Needs to Speak with Someone</title>'
    + '<style type="text/css">'
    + '/*Basics*/'
    + 'body {margin:0px!important;padding:0px!important;display:block!important;min-width:100%!important;width:100%!important;-webkit-text-size-adjust:none;}'
    + 'table {border-spacing:0;mso-table-lspace:0pt;mso-table-rspace:0pt;}'
    + 'table td {border-collapse:collapse;mso-line-height-rule:exactly;}'
    + 'td img {-ms-interpolation-mode:bicubic;width:auto;max-width:auto;height:auto;margin:auto;display:block!important;border:0px;}'
    + 'td p {margin:0;padding:0;}'
    + 'td div {margin:0;padding:0;}'
    + 'td a {text-decoration:none;color:#005ea2;}'
    + '/*Outlook*/'
    + '.ExternalClass {width:100%;}'
    + '.ExternalClass,.ExternalClass p,.ExternalClass span,.ExternalClass font,.ExternalClass td,.ExternalClass div {line-height:inherit;}'
    + '.ReadMsgBody {width:100%;background-color:#ffffff;}'
    + '/* iOS BLUE LINKS */'
    + 'a[x-apple-data-detectors] {color:inherit!important;text-decoration:none!important;font-size:inherit!important;font-family:inherit!important;font-weight:inherit!important;line-height:inherit!important;}'
    + '/*Gmail blue links*/'
    + 'u + #body a {color:inherit;text-decoration:none;font-size:inherit;font-family:inherit;font-weight:inherit;line-height:inherit;}'
    + '/*Buttons fix*/'
    + '.undoreset a, .undoreset a:hover {text-decoration:none!important;}'
    + '.yshortcuts a {border-bottom:none!important;}'
    + '.ios-footer a {color:#aaaaaa!important;text-decoration:none;}'
    + '/*Responsive*/'
    + '@media screen and (max-width:799px) {'
    + '  table.row {width:100%!important;max-width:100%!important;}'
    + '  td.row {width:100%!important;max-width:100%!important;}'
    + '  .img-responsive img {width:100%!important;max-width:100%!important;height:auto!important;margin:auto;}'
    + '  .center-float {float:none!important;margin:auto!important;}'
    + '  .center-text{text-align:center!important;}'
    + '  .container-padding {width:100%!important;padding-left:15px!important;padding-right:15px!important;}'
    + '  .container-padding10 {width:100%!important;padding-left:10px!important;padding-right:10px!important;}'
    + '  .hide-mobile {display:none!important;}'
    + '  .menu-container {text-align:center!important;}'
    + '  .autoheight {height:auto!important;}'
    + '  .m-padding-10 {margin:10px 0!important;}'
    + '  .m-padding-15 {margin:15px 0!important;}'
    + '  .m-padding-20 {margin:20px 0!important;}'
    + '  .m-padding-30 {margin:30px 0!important;}'
    + '  .m-padding-40 {margin:40px 0!important;}'
    + '  .m-padding-50 {margin:50px 0!important;}'
    + '  .m-padding-60 {margin:60px 0!important;}'
    + '  .m-padding-top10 {margin:30px 0 0 0!important;}'
    + '  .m-padding-top15 {margin:15px 0 0 0!important;}'
    + '  .m-padding-top20 {margin:20px 0 0 0!important;}'
    + '  .m-padding-top30 {margin:30px 0 0 0!important;}'
    + '  .m-padding-top40 {margin:40px 0 0 0!important;}'
    + '  .m-padding-top50 {margin:50px 0 0 0!important;}'
    + '  .m-padding-top60 {margin:60px 0 0 0!important;}'
    + '  .m-height10 {font-size:10px!important;line-height:10px!important;height:10px!important;}'
    + '  .m-height15 {font-size:15px!important;line-height:15px!important;height:15px!important;}'
    + '  .m-height20 {font-size:20px!important;line-height:20px!important;height:20px!important;}'
    + '  .m-height25 {font-size:25px!important;line-height:25px!important;height:25px!important;}'
    + '  .m-height30 {font-size:30px!important;line-height:30px!important;height:30px!important;}'
    + '  .rwd-on-mobile {display:inline-block!important;padding:5px;}'
    + '  .center-on-mobile {text-align:center!important;}'
    + '}'
    + '</style>'
    + ''
    + '<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Public Sans:100,200,300,400,500,600,700,800,900,100italic,200italic,300italic,400italic,500italic,600italic,700italic,800italic,900italic"></head>'
    + '<body style="margin-top:0;margin-bottom:0;padding-top:0;padding-bottom:0;width:100%;-webkit-text-size-adjust:100%;-ms-text-size-adjust:100%;" bgcolor="#f0f0f0">'
    + '<span class="preheader-text" style="color:transparent;height:0;max-height:0;max-width:0;opacity:0;overflow:hidden;visibility:hidden;width:0;display:none;mso-hide:all;">We have identified individuals within your group that have requested to speak with someone.</span>'
    + ''
    + '<table border="0" align="center" cellpadding="0" cellspacing="0" width="100%" style="width:100%;max-width:100%;">'
    + '  <tbody><tr><!-- Outer Table -->'
    + '    <td align="center" bgcolor="#F4F4F4">'
    + '                        <table border="0" align="center" cellpadding="0" cellspacing="0" role="presentation" width="100%" style="width:100%;max-width:100%;">'
    + '  <!-- Header -->'
    + '  <tbody><tr>'
    + '    <td align="center" bgcolor="#3a4758" class="container-padding">'
    + '<!-- Content -->'
    + '<table border="0" align="center" cellpadding="0" cellspacing="0" role="presentation" class="row" width="640" style="width:640px;max-width:640px;">'
    + '  <tbody><tr>'
    + '    <td height="40" style="font-size:40px;line-height:40px;"> </td>'
    + '  </tr>'
    + '  <tr>'
    + '    <td align="center">'
    + '      <!-- Logo & Webview -->'
    + '      <table border="0" align="center" cellpadding="0" cellspacing="0" role="presentation" width="100%" style="width:100%;max-width:100%;">'
    + '        <tbody><tr>'
    + '          <td align="center" class="container-padding">'
    + '      <!--[if (gte mso 9)|(IE)]><table border="0" cellpadding="0" cellspacing="0" dir="rtl"><tr><td><![endif]-->'
    + '      <!-- Column -->'
    + '      <table border="0" align="right" cellpadding="0" cellspacing="0" role="presentation" class="row" width="280" style="width:280px;max-width:280px;">'
    + '        <tbody><tr>'
    + '          <td class="center-text" align="right" height="32" style="height:32px;">'
    + '            <a href="#" style="font-family:\'Public Sans\', Arial, Helvetica, sans-serif;font-size:12px;line-height:16px;font-style:italic;font-weight:400;color:#dcddde;text-decoration:none;letter-spacing:0px;">View this email in your browser</a>'
    + '          </td>'
    + '        </tr>'
    + '      </tbody></table>'
    + '      <!-- Column -->'
    + '      <!--[if (gte mso 9)|(IE)]></td><td><![endif]-->'
    + '      <!-- Gap -->'
    + '      <table border="0" align="right" cellpadding="0" cellspacing="0" role="presentation" class="row" width="20" style="width:20px;max-width:20px;">'
    + '        <tbody><tr>'
    + '          <td height="20" style="font-size:20px;line-height:20px;"> </td>'
    + '        </tr>'
    + '      </tbody></table>'
    + '      <!-- Gap -->'
    + '      <!--[if (gte mso 9)|(IE)]></td><td><![endif]-->'
    + '      <!-- Column -->'
    + '      <table border="0" align="right" cellpadding="0" cellspacing="0" role="presentation" class="row" width="340" style="width:340px;max-width:340px;">'
    + '        <tbody><tr>'
    + '          <td align="left" class="center-text">'
    + '            <img style="width:211px;border:0px;display:inline!important;" src="__IMAGE_URL__/logo.png" width="211" border="0" alt="logo">'
    + '          </td>'
    + '        </tr>'
    + '      </tbody></table>'
    + '      <!-- Column -->'
    + '      <!--[if (gte mso 9)|(IE)]></td></tr></table><![endif]-->'
    + '          </td>'
    + '        </tr>'
    + '      </tbody></table>'
    + '      <!-- Logo & Webview -->'
    + '    </td>'
    + '  </tr>'
    + '  <tr>'
    + '    <td height="80" style="font-size:40px;line-height:80px;"> </td>'
    + '  </tr>'
    + '  <tr>'
    + '    <td align="center" class="center-text">'
    + '      <img style="width:218px;border:0px;display:inline!important;" src="__IMAGE_URL__/medical-bubbles.png" width="218" border="0" alt="intro">'
    + '    </td>'
    + '  </tr>'
    + '  <tr>'
    + '    <td height="80" style="font-size:40px;line-height:80px;"> </td>'
    + '  </tr>'
    + '  <tr>'
    + '    <td class="center-text" align="center" style="font-family:\'Public Sans\', Arial, Helvetica, sans-serif;font-size:36px;line-height:40px;font-weight:700;font-style:normal;color:rgb(255, 255, 255);text-decoration:none;letter-spacing:0.75px;">'
    + '        <singleline>'
    + '          <div style="margin: 0px; padding: 0px;"><p style="margin: 0px; padding: 0px;">Individual Needs to Speak with Someone</p><p style="margin: 0px; padding: 0px;">'
    + '          </p></div>'
    + '        </singleline>'
    + '    </td>'
    + '  </tr>'
    + '  <tr>'
    + '    <td height="20" style="font-size:20px;line-height:20px;"> </td>'
    + '  </tr>'
    + '  <tr>'
    + '    <td class="center-text" align="center" style="font-family:\'Public Sans\', Arial, Helvetica, sans-serif;font-size:22px;line-height:29px;font-weight:300;font-style:normal;color:rgb(255, 255, 255);text-decoration:none;letter-spacing:0px;">'
    + '        <singleline>'
    + '          <div style="margin: 0px; padding: 0px;"><p style="margin: 0px; padding: 0px;">We have identified <strong style="color:#7efbe1;">__VALUE__ individual(s) </strong>within your group that have requested to speak with someone.</p><p style="margin: 0px; padding: 0px;">'
    + '          </p></div>'
    + '        </singleline>'
    + '    </td>'
    + '  </tr>'
    + '  <tr>'
    + '    <td height="40" style="font-size:40px;line-height:40px;"> </td>'
    + '  </tr>'
    + '  <tr>'
    + '    <td align="center">'
    + '      <!-- Header Button -->'
    + '      <table border="0" cellspacing="0" cellpadding="0" role="presentation" align="center" class="center-float">'
    + '        <tbody><tr>'
    + '          <td align="center" bgcolor="transparent" style="border-radius:5px; border: 2px solid white;">'
    + '      <!--[if (gte mso 9)|(IE)]>'
    + '        <table border="0" cellpadding="0" cellspacing="0" align="center">'
    + '          <tr>'
    + '            <td align="center" width="50"></td>'
    + '            <td align="center" height="50" style="height:50px;">'
    + '            <![endif]-->'
    + '              <singleline>'
    + '                <a href="__LINK__" target="_blank" style="font-family:\'Public Sans\', Arial, Helvetica, sans-serif;font-size:22px;line-height:29px;font-weight:500;font-style:normal;color:rgb(255, 255, 255);text-decoration:none;letter-spacing:0px;letter-spacing:0px;padding:20px 80px 20px 80px;display:inline-block;"><span>Review Now</span></a>'
    + '              </singleline>'
    + '            <!--[if (gte mso 9)|(IE)]>'
    + '            </td>'
    + '            <td align="center" width="50"></td>'
    + '          </tr>'
    + '        </table>'
    + '      <![endif]-->'
    + '          </td>'
    + '        </tr>'
    + '      </tbody></table>'
    + '      <!-- Header Button -->'
    + '    </td>'
    + '  </tr>'
    + '  <tr>'
    + '    <td height="100" style="font-size:40px;line-height:60px;"> </td>'
    + '  </tr>'
    + '</tbody></table>'
    + '<!-- Content -->'
    + '    </td>'
    + '  </tr>'
    + '</tbody></table><table border="0" align="center" cellpadding="0" cellspacing="0" role="presentation" width="100%" style="width:100%;max-width:100%;">'
    + '  <!-- Footer -->'
    + '  <tbody><tr>'
    + '    <td align="center" bgcolor="#f0f0f0" class="container-padding">'
    + '<!-- Content -->'
    + '<table border="0" align="center" cellpadding="0" cellspacing="0" role="presentation" class="row" width="640" style="width:640px;max-width:640px;">'
    + '  <tbody><tr>'
    + '    <td height="50" style="font-size:50px;line-height:50px;"> </td>'
    + '  </tr>'
    + ''
    + ''
    + '  <tr style="">'
    + '    <td class="center-text" align="center" style="font-family:\'Public Sans\', Arial, Helvetica, sans-serif;font-size:14px;line-height:26px;font-weight:300;font-style:normal;color:rgb(110, 110, 110);text-decoration:none;letter-spacing:0px;">'
    + '      <multiline>'
    + '        <div style="margin: 0px; padding: 0px;"><p style="margin: 0px; padding: 0px;">This email was sent because you are a registered member of StatusEngine and have opted in to receive email communications. If you wish to change these settings, you can adjust your <a href="#" target="_blank" style="text-decoration: none;">email preferences</a> any time.</p><p style="margin: 0px; padding: 0px;"><br></p><p style="margin: 0px; padding: 0px;">Please send any feedback or bug reports to  <a href="mailto:support@mystatusengine.gov" target="_blank" style="text-decoration: none;">support@mystatusengine.gov</a></p><p style="margin: 0px; padding: 0px;">'
    + '        </p></div>'
    + '      </multiline>'
    + '    </td>'
    + '  </tr>'
    + '  <tr>'
    + '    <td height="30" style="font-size:30px;line-height:30px;"> </td>'
    + '  </tr>'
    + '  <tr>'
    + '    <td height="50" style="font-size:50px;line-height:50px;"> </td>'
    + '  </tr>'
    + '</tbody></table>'
    + '<!-- Content -->'
    + '    </td>'
    + '  </tr>'
    + '</tbody></table></td>'
    + '  </tr><!-- Outer-Table -->'
    + '</tbody></table>'
    + '</body>'
    + '</html>',
  emailTextTemplate: 'We have identified __VALUE__ individual(s) within your group that have requested to speak with someone. __LINK__',
  dashboardUuid: '',
  defaultMaxDailyCount: 1,
  defaultThreshold: 1,
  defaultMinTimeBetweenAlerts: 0,
}, {
  id: 'symptomTrendingAlert',
  uiSort: 3,
  uiName: 'Symptom Trending',
  uiDescription: 'Alert me when symptom trends are identified within the group.',
  uiSettingsTemplate: 'Alert me by {type} when {threshold} or more symptoms are trending.',
  smsTemplate: 'StatusEngine - We have identified __VALUE__ new symptom(s) trending within your group.',
  emailHtmlTemplate: '<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">'
    + '<html xmlns="http://www.w3.org/1999/xhtml" xmlns:v="urn:schemas-microsoft-com:vml" xmlns:o="urn:schemas-microsoft-com:office:office">'
    + '<head>'
    + '<!--[if (gte mso 9)|(IE)]>'
    + '  <xml>'
    + '    <o:OfficeDocumentSettings>'
    + '    <o:AllowPNG></o:AllowPNG>'
    + '    <o:PixelsPerInch>96</o:PixelsPerInch>'
    + '  </o:OfficeDocumentSettings>'
    + '</xml>'
    + '<![endif]-->'
    + '<meta http-equiv="Content-Type" content="text/html;charset=UTF-8">'
    + '<meta name="viewport" content="width=device-width, initial-scale=1"> <!-- So that mobile will display zoomed in -->'
    + '<meta http-equiv="X-UA-Compatible" content="IE=edge"> <!-- enable media queries for windows phone 8 -->'
    + '<meta name="format-detection" content="telephone=no"> <!-- disable auto telephone linking in iOS -->'
    + '<meta name="format-detection" content="date=no"> <!-- disable auto date linking in iOS -->'
    + '<meta name="format-detection" content="address=no"> <!-- disable auto address linking in iOS -->'
    + '<meta name="format-detection" content="email=no"> <!-- disable auto email linking in iOS -->'
    + '<title>Symptom Trending</title>'
    + '<style type="text/css">'
    + '/*Basics*/'
    + 'body {margin:0px!important;padding:0px!important;display:block!important;min-width:100%!important;width:100%!important;-webkit-text-size-adjust:none;}'
    + 'table {border-spacing:0;mso-table-lspace:0pt;mso-table-rspace:0pt;}'
    + 'table td {border-collapse:collapse;mso-line-height-rule:exactly;}'
    + 'td img {-ms-interpolation-mode:bicubic;width:auto;max-width:auto;height:auto;margin:auto;display:block!important;border:0px;}'
    + 'td p {margin:0;padding:0;}'
    + 'td div {margin:0;padding:0;}'
    + 'td a {text-decoration:none;color:#005ea2;}'
    + '/*Outlook*/'
    + '.ExternalClass {width:100%;}'
    + '.ExternalClass,.ExternalClass p,.ExternalClass span,.ExternalClass font,.ExternalClass td,.ExternalClass div {line-height:inherit;}'
    + '.ReadMsgBody {width:100%;background-color:#ffffff;}'
    + '/* iOS BLUE LINKS */'
    + 'a[x-apple-data-detectors] {color:inherit!important;text-decoration:none!important;font-size:inherit!important;font-family:inherit!important;font-weight:inherit!important;line-height:inherit!important;}'
    + '/*Gmail blue links*/'
    + 'u + #body a {color:inherit;text-decoration:none;font-size:inherit;font-family:inherit;font-weight:inherit;line-height:inherit;}'
    + '/*Buttons fix*/'
    + '.undoreset a, .undoreset a:hover {text-decoration:none!important;}'
    + '.yshortcuts a {border-bottom:none!important;}'
    + '.ios-footer a {color:#aaaaaa!important;text-decoration:none;}'
    + '/*Responsive*/'
    + '@media screen and (max-width:799px) {'
    + '  table.row {width:100%!important;max-width:100%!important;}'
    + '  td.row {width:100%!important;max-width:100%!important;}'
    + '  .img-responsive img {width:100%!important;max-width:100%!important;height:auto!important;margin:auto;}'
    + '  .center-float {float:none!important;margin:auto!important;}'
    + '  .center-text{text-align:center!important;}'
    + '  .container-padding {width:100%!important;padding-left:15px!important;padding-right:15px!important;}'
    + '  .container-padding10 {width:100%!important;padding-left:10px!important;padding-right:10px!important;}'
    + '  .hide-mobile {display:none!important;}'
    + '  .menu-container {text-align:center!important;}'
    + '  .autoheight {height:auto!important;}'
    + '  .m-padding-10 {margin:10px 0!important;}'
    + '  .m-padding-15 {margin:15px 0!important;}'
    + '  .m-padding-20 {margin:20px 0!important;}'
    + '  .m-padding-30 {margin:30px 0!important;}'
    + '  .m-padding-40 {margin:40px 0!important;}'
    + '  .m-padding-50 {margin:50px 0!important;}'
    + '  .m-padding-60 {margin:60px 0!important;}'
    + '  .m-padding-top10 {margin:30px 0 0 0!important;}'
    + '  .m-padding-top15 {margin:15px 0 0 0!important;}'
    + '  .m-padding-top20 {margin:20px 0 0 0!important;}'
    + '  .m-padding-top30 {margin:30px 0 0 0!important;}'
    + '  .m-padding-top40 {margin:40px 0 0 0!important;}'
    + '  .m-padding-top50 {margin:50px 0 0 0!important;}'
    + '  .m-padding-top60 {margin:60px 0 0 0!important;}'
    + '  .m-height10 {font-size:10px!important;line-height:10px!important;height:10px!important;}'
    + '  .m-height15 {font-size:15px!important;line-height:15px!important;height:15px!important;}'
    + '  .m-height20 {font-size:20px!important;line-height:20px!important;height:20px!important;}'
    + '  .m-height25 {font-size:25px!important;line-height:25px!important;height:25px!important;}'
    + '  .m-height30 {font-size:30px!important;line-height:30px!important;height:30px!important;}'
    + '  .rwd-on-mobile {display:inline-block!important;padding:5px;}'
    + '  .center-on-mobile {text-align:center!important;}'
    + '}'
    + '</style>'
    + ''
    + '<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Public Sans:100,200,300,400,500,600,700,800,900,100italic,200italic,300italic,400italic,500italic,600italic,700italic,800italic,900italic"></head>'
    + '<body style="margin-top:0;margin-bottom:0;padding-top:0;padding-bottom:0;width:100%;-webkit-text-size-adjust:100%;-ms-text-size-adjust:100%;" bgcolor="#f0f0f0">'
    + '<span class="preheader-text" style="color:transparent;height:0;max-height:0;max-width:0;opacity:0;overflow:hidden;visibility:hidden;width:0;display:none;mso-hide:all;">We have identified <strong style="color:#7efbe1;">__VALUE__ individual(s) </strong> within your group.</span>'
    + ''
    + '<table border="0" align="center" cellpadding="0" cellspacing="0" width="100%" style="width:100%;max-width:100%;">'
    + '  <tbody><tr><!-- Outer Table -->'
    + '    <td align="center" bgcolor="#F4F4F4">'
    + '                        <table border="0" align="center" cellpadding="0" cellspacing="0" role="presentation" width="100%" style="width:100%;max-width:100%;">'
    + '  <!-- Header -->'
    + '  <tbody><tr>'
    + '    <td align="center" bgcolor="#3a4758" class="container-padding">'
    + '<!-- Content -->'
    + '<table border="0" align="center" cellpadding="0" cellspacing="0" role="presentation" class="row" width="640" style="width:640px;max-width:640px;">'
    + '  <tbody><tr>'
    + '    <td height="40" style="font-size:40px;line-height:40px;"> </td>'
    + '  </tr>'
    + '  <tr>'
    + '    <td align="center">'
    + '      <!-- Logo & Webview -->'
    + '      <table border="0" align="center" cellpadding="0" cellspacing="0" role="presentation" width="100%" style="width:100%;max-width:100%;">'
    + '        <tbody><tr>'
    + '          <td align="center" class="container-padding">'
    + '      <!--[if (gte mso 9)|(IE)]><table border="0" cellpadding="0" cellspacing="0" dir="rtl"><tr><td><![endif]-->'
    + '      <!-- Column -->'
    + '      <table border="0" align="right" cellpadding="0" cellspacing="0" role="presentation" class="row" width="280" style="width:280px;max-width:280px;">'
    + '        <tbody><tr>'
    + '          <td class="center-text" align="right" height="32" style="height:32px;">'
    + '            <a href="#" style="font-family:\'Public Sans\', Arial, Helvetica, sans-serif;font-size:12px;line-height:16px;font-style:italic;font-weight:400;color:#dcddde;text-decoration:none;letter-spacing:0px;">View this email in your browser</a>'
    + '          </td>'
    + '        </tr>'
    + '      </tbody></table>'
    + '      <!-- Column -->'
    + '      <!--[if (gte mso 9)|(IE)]></td><td><![endif]-->'
    + '      <!-- Gap -->'
    + '      <table border="0" align="right" cellpadding="0" cellspacing="0" role="presentation" class="row" width="20" style="width:20px;max-width:20px;">'
    + '        <tbody><tr>'
    + '          <td height="20" style="font-size:20px;line-height:20px;"> </td>'
    + '        </tr>'
    + '      </tbody></table>'
    + '      <!-- Gap -->'
    + '      <!--[if (gte mso 9)|(IE)]></td><td><![endif]-->'
    + '      <!-- Column -->'
    + '      <table border="0" align="right" cellpadding="0" cellspacing="0" role="presentation" class="row" width="340" style="width:340px;max-width:340px;">'
    + '        <tbody><tr>'
    + '          <td align="left" class="center-text">'
    + '            <img style="width:211px;border:0px;display:inline!important;" src="__IMAGE_URL__/logo.png" width="211" border="0" alt="logo">'
    + '          </td>'
    + '        </tr>'
    + '      </tbody></table>'
    + '      <!-- Column -->'
    + '      <!--[if (gte mso 9)|(IE)]></td></tr></table><![endif]-->'
    + '          </td>'
    + '        </tr>'
    + '      </tbody></table>'
    + '      <!-- Logo & Webview -->'
    + '    </td>'
    + '  </tr>'
    + '  <tr>'
    + '    <td height="80" style="font-size:40px;line-height:80px;"> </td>'
    + '  </tr>'
    + '  <tr>'
    + '    <td align="center" class="center-text">'
    + '      <img style="width:218px;border:0px;display:inline!important;" src="__IMAGE_URL__/trending-chart.png" width="218" border="0" alt="intro">'
    + '    </td>'
    + '  </tr>'
    + '  <tr>'
    + '    <td height="80" style="font-size:40px;line-height:80px;"> </td>'
    + '  </tr>'
    + '  <tr>'
    + '    <td class="center-text" align="center" style="font-family:\'Public Sans\', Arial, Helvetica, sans-serif;font-size:36px;line-height:40px;font-weight:700;font-style:normal;color:rgb(255, 255, 255);text-decoration:none;letter-spacing:0.75px;">'
    + '        <singleline>'
    + '          <div style="margin: 0px; padding: 0px;"><p style="margin: 0px; padding: 0px;">Symptom Trending</p><p style="margin: 0px; padding: 0px;">'
    + '          </p></div>'
    + '        </singleline>'
    + '    </td>'
    + '  </tr>'
    + '  <tr>'
    + '    <td height="20" style="font-size:20px;line-height:20px;"> </td>'
    + '  </tr>'
    + '  <tr>'
    + '    <td class="center-text" align="center" style="font-family:\'Public Sans\', Arial, Helvetica, sans-serif;font-size:22px;line-height:29px;font-weight:300;font-style:normal;color:rgb(255, 255, 255);text-decoration:none;letter-spacing:0px;">'
    + '        <singleline>'
    + '          <div style="margin: 0px; padding: 0px;"><p style="margin: 0px; padding: 0px;">We have identified <strong style="color:#7efbe1;">__VALUE__ new symptom(s) </strong>trending within your group.</p><p style="margin: 0px; padding: 0px;">'
    + '          </p></div>'
    + '        </singleline>'
    + '    </td>'
    + '  </tr>'
    + '  <tr>'
    + '    <td height="40" style="font-size:40px;line-height:40px;"> </td>'
    + '  </tr>'
    + '  <tr>'
    + '    <td align="center">'
    + '      <!-- Header Button -->'
    + '      <table border="0" cellspacing="0" cellpadding="0" role="presentation" align="center" class="center-float">'
    + '        <tbody><tr>'
    + '          <td align="center" bgcolor="transparent" style="border-radius:5px; border: 2px solid white;">'
    + '      <!--[if (gte mso 9)|(IE)]>'
    + '        <table border="0" cellpadding="0" cellspacing="0" align="center">'
    + '          <tr>'
    + '            <td align="center" width="50"></td>'
    + '            <td align="center" height="50" style="height:50px;">'
    + '            <![endif]-->'
    + '              <singleline>'
    + '                <a href="__LINK__" target="_blank" style="font-family:\'Public Sans\', Arial, Helvetica, sans-serif;font-size:22px;line-height:29px;font-weight:500;font-style:normal;color:rgb(255, 255, 255);text-decoration:none;letter-spacing:0px;letter-spacing:0px;padding:20px 80px 20px 80px;display:inline-block;"><span>Review Now</span></a>'
    + '              </singleline>'
    + '            <!--[if (gte mso 9)|(IE)]>'
    + '            </td>'
    + '            <td align="center" width="50"></td>'
    + '          </tr>'
    + '        </table>'
    + '      <![endif]-->'
    + '          </td>'
    + '        </tr>'
    + '      </tbody></table>'
    + '      <!-- Header Button -->'
    + '    </td>'
    + '  </tr>'
    + '  <tr>'
    + '    <td height="100" style="font-size:40px;line-height:60px;"> </td>'
    + '  </tr>'
    + '</tbody></table>'
    + '<!-- Content -->'
    + '    </td>'
    + '  </tr>'
    + '</tbody></table><table border="0" align="center" cellpadding="0" cellspacing="0" role="presentation" width="100%" style="width:100%;max-width:100%;">'
    + '  <!-- Footer -->'
    + '  <tbody><tr>'
    + '    <td align="center" bgcolor="#f0f0f0" class="container-padding">'
    + '<!-- Content -->'
    + '<table border="0" align="center" cellpadding="0" cellspacing="0" role="presentation" class="row" width="640" style="width:640px;max-width:640px;">'
    + '  <tbody><tr>'
    + '    <td height="50" style="font-size:50px;line-height:50px;"> </td>'
    + '  </tr>'
    + ''
    + ''
    + '  <tr style="">'
    + '    <td class="center-text" align="center" style="font-family:\'Public Sans\', Arial, Helvetica, sans-serif;font-size:14px;line-height:26px;font-weight:300;font-style:normal;color:rgb(110, 110, 110);text-decoration:none;letter-spacing:0px;">'
    + '      <multiline>'
    + '        <div style="margin: 0px; padding: 0px;"><p style="margin: 0px; padding: 0px;">This email was sent because you are a registered member of StatusEngine and have opted in to receive email communications. If you wish to change these settings, you can adjust your <a href="#" target="_blank" style="text-decoration: none;">email preferences</a> any time.</p><p style="margin: 0px; padding: 0px;"><br></p><p style="margin: 0px; padding: 0px;">Please send any feedback or bug reports to  <a href="mailto:support@mystatusengine.gov" target="_blank" style="text-decoration: none;">support@mystatusengine.gov</a></p><p style="margin: 0px; padding: 0px;">'
    + '        </p></div>'
    + '      </multiline>'
    + '    </td>'
    + '  </tr>'
    + '  <tr>'
    + '    <td height="30" style="font-size:30px;line-height:30px;"> </td>'
    + '  </tr>'
    + '  <tr>'
    + '    <td height="50" style="font-size:50px;line-height:50px;"> </td>'
    + '  </tr>'
    + '</tbody></table>'
    + '<!-- Content -->'
    + '    </td>'
    + '  </tr>'
    + '</tbody></table></td>'
    + '  </tr><!-- Outer-Table -->'
    + '</tbody></table>'
    + '</body>'
    + '</html>',
  emailTextTemplate: 'We have identified __VALUE__ symptom(s) trending within your group. __LINK__',
  dashboardUuid: '',
  defaultMaxDailyCount: -1,
  defaultThreshold: 1,
  defaultMinTimeBetweenAlerts: -1,
}, {
  id: 'musterAlert',
  uiSort: 4,
  uiName: 'Low Muster Rate',
  uiDescription: 'Alert me when at least one unit fails muster compliance.',
  uiSettingsTemplate: 'Alert me by {type} when {threshold}% of a single unit has not mustered.',
  smsTemplate: 'StatusEngine - We have identified that there is a unit with less than __VALUE__ percent muster compliance.',
  emailHtmlTemplate: '<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">'
    + '<html xmlns="http://www.w3.org/1999/xhtml" xmlns:v="urn:schemas-microsoft-com:vml" xmlns:o="urn:schemas-microsoft-com:office:office">'
    + '<head>'
    + '<!--[if (gte mso 9)|(IE)]>'
    + '  <xml>'
    + '    <o:OfficeDocumentSettings>'
    + '    <o:AllowPNG></o:AllowPNG>'
    + '    <o:PixelsPerInch>96</o:PixelsPerInch>'
    + '  </o:OfficeDocumentSettings>'
    + '</xml>'
    + '<![endif]-->'
    + '<meta http-equiv="Content-Type" content="text/html;charset=UTF-8">'
    + '<meta name="viewport" content="width=device-width, initial-scale=1"> <!-- So that mobile will display zoomed in -->'
    + '<meta http-equiv="X-UA-Compatible" content="IE=edge"> <!-- enable media queries for windows phone 8 -->'
    + '<meta name="format-detection" content="telephone=no"> <!-- disable auto telephone linking in iOS -->'
    + '<meta name="format-detection" content="date=no"> <!-- disable auto date linking in iOS -->'
    + '<meta name="format-detection" content="address=no"> <!-- disable auto address linking in iOS -->'
    + '<meta name="format-detection" content="email=no"> <!-- disable auto email linking in iOS -->'
    + '<title>Low Muster Rate</title>'
    + '<style type="text/css">'
    + '/*Basics*/'
    + 'body {margin:0px!important;padding:0px!important;display:block!important;min-width:100%!important;width:100%!important;-webkit-text-size-adjust:none;}'
    + 'table {border-spacing:0;mso-table-lspace:0pt;mso-table-rspace:0pt;}'
    + 'table td {border-collapse:collapse;mso-line-height-rule:exactly;}'
    + 'td img {-ms-interpolation-mode:bicubic;width:auto;max-width:auto;height:auto;margin:auto;display:block!important;border:0px;}'
    + 'td p {margin:0;padding:0;}'
    + 'td div {margin:0;padding:0;}'
    + 'td a {text-decoration:none;color:#005ea2;}'
    + '/*Outlook*/'
    + '.ExternalClass {width:100%;}'
    + '.ExternalClass,.ExternalClass p,.ExternalClass span,.ExternalClass font,.ExternalClass td,.ExternalClass div {line-height:inherit;}'
    + '.ReadMsgBody {width:100%;background-color:#ffffff;}'
    + '/* iOS BLUE LINKS */'
    + 'a[x-apple-data-detectors] {color:inherit!important;text-decoration:none!important;font-size:inherit!important;font-family:inherit!important;font-weight:inherit!important;line-height:inherit!important;}'
    + '/*Gmail blue links*/'
    + 'u + #body a {color:inherit;text-decoration:none;font-size:inherit;font-family:inherit;font-weight:inherit;line-height:inherit;}'
    + '/*Buttons fix*/'
    + '.undoreset a, .undoreset a:hover {text-decoration:none!important;}'
    + '.yshortcuts a {border-bottom:none!important;}'
    + '.ios-footer a {color:#aaaaaa!important;text-decoration:none;}'
    + '/*Responsive*/'
    + '@media screen and (max-width:799px) {'
    + '  table.row {width:100%!important;max-width:100%!important;}'
    + '  td.row {width:100%!important;max-width:100%!important;}'
    + '  .img-responsive img {width:100%!important;max-width:100%!important;height:auto!important;margin:auto;}'
    + '  .center-float {float:none!important;margin:auto!important;}'
    + '  .center-text{text-align:center!important;}'
    + '  .container-padding {width:100%!important;padding-left:15px!important;padding-right:15px!important;}'
    + '  .container-padding10 {width:100%!important;padding-left:10px!important;padding-right:10px!important;}'
    + '  .hide-mobile {display:none!important;}'
    + '  .menu-container {text-align:center!important;}'
    + '  .autoheight {height:auto!important;}'
    + '  .m-padding-10 {margin:10px 0!important;}'
    + '  .m-padding-15 {margin:15px 0!important;}'
    + '  .m-padding-20 {margin:20px 0!important;}'
    + '  .m-padding-30 {margin:30px 0!important;}'
    + '  .m-padding-40 {margin:40px 0!important;}'
    + '  .m-padding-50 {margin:50px 0!important;}'
    + '  .m-padding-60 {margin:60px 0!important;}'
    + '  .m-padding-top10 {margin:30px 0 0 0!important;}'
    + '  .m-padding-top15 {margin:15px 0 0 0!important;}'
    + '  .m-padding-top20 {margin:20px 0 0 0!important;}'
    + '  .m-padding-top30 {margin:30px 0 0 0!important;}'
    + '  .m-padding-top40 {margin:40px 0 0 0!important;}'
    + '  .m-padding-top50 {margin:50px 0 0 0!important;}'
    + '  .m-padding-top60 {margin:60px 0 0 0!important;}'
    + '  .m-height10 {font-size:10px!important;line-height:10px!important;height:10px!important;}'
    + '  .m-height15 {font-size:15px!important;line-height:15px!important;height:15px!important;}'
    + '  .m-height20 {font-size:20px!important;line-height:20px!important;height:20px!important;}'
    + '  .m-height25 {font-size:25px!important;line-height:25px!important;height:25px!important;}'
    + '  .m-height30 {font-size:30px!important;line-height:30px!important;height:30px!important;}'
    + '  .rwd-on-mobile {display:inline-block!important;padding:5px;}'
    + '  .center-on-mobile {text-align:center!important;}'
    + '}'
    + '</style>'
    + ''
    + '<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Public Sans:100,200,300,400,500,600,700,800,900,100italic,200italic,300italic,400italic,500italic,600italic,700italic,800italic,900italic"></head>'
    + '<body style="margin-top:0;margin-bottom:0;padding-top:0;padding-bottom:0;width:100%;-webkit-text-size-adjust:100%;-ms-text-size-adjust:100%;" bgcolor="#f0f0f0">'
    + '<span class="preheader-text" style="color:transparent;height:0;max-height:0;max-width:0;opacity:0;overflow:hidden;visibility:hidden;width:0;display:none;mso-hide:all;">We have identified at least one unit in your group with a low muster rate.</span>'
    + ''
    + '<table border="0" align="center" cellpadding="0" cellspacing="0" width="100%" style="width:100%;max-width:100%;">'
    + '  <tbody><tr><!-- Outer Table -->'
    + '    <td align="center" bgcolor="#F4F4F4">'
    + '                        <table border="0" align="center" cellpadding="0" cellspacing="0" role="presentation" width="100%" style="width:100%;max-width:100%;">'
    + '  <!-- Header -->'
    + '  <tbody><tr>'
    + '    <td align="center" bgcolor="#3a4758" class="container-padding">'
    + '<!-- Content -->'
    + '<table border="0" align="center" cellpadding="0" cellspacing="0" role="presentation" class="row" width="640" style="width:640px;max-width:640px;">'
    + '  <tbody><tr>'
    + '    <td height="40" style="font-size:40px;line-height:40px;"> </td>'
    + '  </tr>'
    + '  <tr>'
    + '    <td align="center">'
    + '      <!-- Logo & Webview -->'
    + '      <table border="0" align="center" cellpadding="0" cellspacing="0" role="presentation" width="100%" style="width:100%;max-width:100%;">'
    + '        <tbody><tr>'
    + '          <td align="center" class="container-padding">'
    + '      <!--[if (gte mso 9)|(IE)]><table border="0" cellpadding="0" cellspacing="0" dir="rtl"><tr><td><![endif]-->'
    + '      <!-- Column -->'
    + '      <table border="0" align="right" cellpadding="0" cellspacing="0" role="presentation" class="row" width="280" style="width:280px;max-width:280px;">'
    + '        <tbody><tr>'
    + '          <td class="center-text" align="right" height="32" style="height:32px;">'
    + '            <a href="#" style="font-family:\'Public Sans\', Arial, Helvetica, sans-serif;font-size:12px;line-height:16px;font-style:italic;font-weight:400;color:#dcddde;text-decoration:none;letter-spacing:0px;">View this email in your browser</a>'
    + '          </td>'
    + '        </tr>'
    + '      </tbody></table>'
    + '      <!-- Column -->'
    + '      <!--[if (gte mso 9)|(IE)]></td><td><![endif]-->'
    + '      <!-- Gap -->'
    + '      <table border="0" align="right" cellpadding="0" cellspacing="0" role="presentation" class="row" width="20" style="width:20px;max-width:20px;">'
    + '        <tbody><tr>'
    + '          <td height="20" style="font-size:20px;line-height:20px;"> </td>'
    + '        </tr>'
    + '      </tbody></table>'
    + '      <!-- Gap -->'
    + '      <!--[if (gte mso 9)|(IE)]></td><td><![endif]-->'
    + '      <!-- Column -->'
    + '      <table border="0" align="right" cellpadding="0" cellspacing="0" role="presentation" class="row" width="340" style="width:340px;max-width:340px;">'
    + '        <tbody><tr>'
    + '          <td align="left" class="center-text">'
    + '            <img style="width:211px;border:0px;display:inline!important;" src="__IMAGE_URL__/logo.png" width="211" border="0" alt="logo">'
    + '          </td>'
    + '        </tr>'
    + '      </tbody></table>'
    + '      <!-- Column -->'
    + '      <!--[if (gte mso 9)|(IE)]></td></tr></table><![endif]-->'
    + '          </td>'
    + '        </tr>'
    + '      </tbody></table>'
    + '      <!-- Logo & Webview -->'
    + '    </td>'
    + '  </tr>'
    + '  <tr>'
    + '    <td height="80" style="font-size:40px;line-height:80px;"> </td>'
    + '  </tr>'
    + '  <tr>'
    + '    <td align="center" class="center-text">'
    + '      <img style="width:218px;border:0px;display:inline!important;" src="__IMAGE_URL__/low-percentage.png" width="218" border="0" alt="intro">'
    + '    </td>'
    + '  </tr>'
    + '  <tr>'
    + '    <td height="80" style="font-size:40px;line-height:80px;"> </td>'
    + '  </tr>'
    + '  <tr>'
    + '    <td class="center-text" align="center" style="font-family:\'Public Sans\', Arial, Helvetica, sans-serif;font-size:36px;line-height:40px;font-weight:700;font-style:normal;color:rgb(255, 255, 255);text-decoration:none;letter-spacing:0.75px;">'
    + '        <singleline>'
    + '          <div style="margin: 0px; padding: 0px;"><p style="margin: 0px; padding: 0px;">Low Muster Rate</p><p style="margin: 0px; padding: 0px;">'
    + '          </p></div>'
    + '        </singleline>'
    + '    </td>'
    + '  </tr>'
    + '  <tr>'
    + '    <td height="20" style="font-size:20px;line-height:20px;"> </td>'
    + '  </tr>'
    + '  <tr>'
    + '    <td class="center-text" align="center" style="font-family:\'Public Sans\', Arial, Helvetica, sans-serif;font-size:22px;line-height:29px;font-weight:300;font-style:normal;color:rgb(255, 255, 255);text-decoration:none;letter-spacing:0px;">'
    + '        <singleline>'
    + '          <div style="margin: 0px; padding: 0px;"><p style="margin: 0px; padding: 0px;">We have identified that there is a unit with less than <strong style="color:#7efbe1;">__VALUE__ percent</strong> muster compliance.</p><p style="margin: 0px; padding: 0px;">'
    + '          </p></div>'
    + '        </singleline>'
    + '    </td>'
    + '  </tr>'
    + '  <tr>'
    + '    <td height="40" style="font-size:40px;line-height:40px;"> </td>'
    + '  </tr>'
    + '  <tr>'
    + '    <td align="center">'
    + '      <!-- Header Button -->'
    + '      <table border="0" cellspacing="0" cellpadding="0" role="presentation" align="center" class="center-float">'
    + '        <tbody><tr>'
    + '          <td align="center" bgcolor="transparent" style="border-radius:5px; border: 2px solid white;">'
    + '      <!--[if (gte mso 9)|(IE)]>'
    + '        <table border="0" cellpadding="0" cellspacing="0" align="center">'
    + '          <tr>'
    + '            <td align="center" width="50"></td>'
    + '            <td align="center" height="50" style="height:50px;">'
    + '            <![endif]-->'
    + '              <singleline>'
    + '                <a href="__LINK__" target="_blank" style="font-family:\'Public Sans\', Arial, Helvetica, sans-serif;font-size:22px;line-height:29px;font-weight:500;font-style:normal;color:rgb(255, 255, 255);text-decoration:none;letter-spacing:0px;letter-spacing:0px;padding:20px 80px 20px 80px;display:inline-block;"><span>Review Now</span></a>'
    + '              </singleline>'
    + '            <!--[if (gte mso 9)|(IE)]>'
    + '            </td>'
    + '            <td align="center" width="50"></td>'
    + '          </tr>'
    + '        </table>'
    + '      <![endif]-->'
    + '          </td>'
    + '        </tr>'
    + '      </tbody></table>'
    + '      <!-- Header Button -->'
    + '    </td>'
    + '  </tr>'
    + '  <tr>'
    + '    <td height="100" style="font-size:40px;line-height:60px;"> </td>'
    + '  </tr>'
    + '</tbody></table>'
    + '<!-- Content -->'
    + '    </td>'
    + '  </tr>'
    + '</tbody></table><table border="0" align="center" cellpadding="0" cellspacing="0" role="presentation" width="100%" style="width:100%;max-width:100%;">'
    + '  <!-- Footer -->'
    + '  <tbody><tr>'
    + '    <td align="center" bgcolor="#f0f0f0" class="container-padding">'
    + '<!-- Content -->'
    + '<table border="0" align="center" cellpadding="0" cellspacing="0" role="presentation" class="row" width="640" style="width:640px;max-width:640px;">'
    + '  <tbody><tr>'
    + '    <td height="50" style="font-size:50px;line-height:50px;"> </td>'
    + '  </tr>'
    + ''
    + ''
    + '  <tr style="">'
    + '    <td class="center-text" align="center" style="font-family:\'Public Sans\', Arial, Helvetica, sans-serif;font-size:14px;line-height:26px;font-weight:300;font-style:normal;color:rgb(110, 110, 110);text-decoration:none;letter-spacing:0px;">'
    + '      <multiline>'
    + '        <div style="margin: 0px; padding: 0px;"><p style="margin: 0px; padding: 0px;">This email was sent because you are a registered member of StatusEngine and have opted in to receive email communications. If you wish to change these settings, you can adjust your <a href="#" target="_blank" style="text-decoration: none;">email preferences</a> any time.</p><p style="margin: 0px; padding: 0px;"><br></p><p style="margin: 0px; padding: 0px;">Please send any feedback or bug reports to  <a href="mailto:support@mystatusengine.gov" target="_blank" style="text-decoration: none;">support@mystatusengine.gov</a></p><p style="margin: 0px; padding: 0px;">'
    + '        </p></div>'
    + '      </multiline>'
    + '    </td>'
    + '  </tr>'
    + '  <tr>'
    + '    <td height="30" style="font-size:30px;line-height:30px;"> </td>'
    + '  </tr>'
    + '  <tr>'
    + '    <td height="50" style="font-size:50px;line-height:50px;"> </td>'
    + '  </tr>'
    + '</tbody></table>'
    + '<!-- Content -->'
    + '    </td>'
    + '  </tr>'
    + '</tbody></table></td>'
    + '  </tr><!-- Outer-Table -->'
    + '</tbody></table>'
    + '</body>'
    + '</html>',
  emailTextTemplate: 'We have identified that there is a unit with less than __VALUE__ percent muster compliance. __LINK__',
  dashboardUuid: '',
  defaultMaxDailyCount: 1,
  defaultThreshold: 15,
  defaultMinTimeBetweenAlerts: 0,
}];
