services:
  postgis-dds:
    image: kartoza/postgis:11.5-2.5
    container_name: postgis-dds
    env_file:
      - system.env
    ports:
      - "5432:5432"
    #  volumes:
    #    -  ./data/postgres_data:/var/lib/postgresql
    restart: always
