services:
  postgres-dds:
    image: postgres:11.12
    container_name: postgres-dds
    env_file:
      - system.env
    ports:
      - "5432:5432"
    #  volumes:
    #    -  ./data/postgres_data:/var/lib/postgresql
    restart: always
