import { MigrationInterface, QueryRunner } from 'typeorm';

export class RemoveObservationUnit1634022746013 implements MigrationInterface {

  name = 'RemoveObservationUnit1634022746013';

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`DROP INDEX "observation-unit"`);
    await queryRunner.query(`ALTER TABLE "observation" DROP COLUMN "unit"`);
    const orgs = await queryRunner.query(`SELECT id FROM "org"`);
    for (const org of orgs) {
      await queryRunner.query(
        `UPDATE "report_schema" SET "columns"=$1 WHERE "id"=$2 AND "org_id"=$3`,
        [JSON.stringify(newDefaultReportSchema.columns), newDefaultReportSchema.id, org.id],
      );
    }
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`ALTER TABLE "observation" ADD "unit" character varying(300) NOT NULL`);
    await queryRunner.query(`CREATE INDEX "observation-unit" ON "observation" ("unit") `);
    const orgs = await queryRunner.query(`SELECT id FROM "org"`);
    for (const org of orgs) {
      await queryRunner.query(
        `UPDATE "report_schema" SET "columns"=$1 WHERE "id"=$2 AND "org_id"=$3`,
        [JSON.stringify(oldDefaultReportSchema.columns), oldDefaultReportSchema.id, org.id],
      );
    }
  }

}

enum ColumnType {
  String = 'string',
  Number = 'number',
  Date = 'date',
  DateTime = 'datetime',
  Boolean = 'boolean',
  Enum = 'enum',
}

const newDefaultReportSchema = {
  id: 'es6ddssymptomobs',
  columns: [{
    keyPath: ['Category'],
    name: 'Category',
    displayName: 'Category',
    type: ColumnType.String,
    pii: true,
    phi: true,
    required: false,
    custom: true,
    updatable: false,
  }, {
    keyPath: ['Score'],
    name: 'Score',
    displayName: 'Score',
    type: ColumnType.Number,
    pii: true,
    phi: true,
    required: false,
    custom: true,
    updatable: false,
  }, {
    keyPath: ['Details', 'Affiliation'],
    name: 'Affiliation',
    displayName: 'Affiliation',
    type: ColumnType.String,
    pii: false,
    phi: false,
    otherField: true,
    required: false,
    custom: true,
    updatable: false,
  }, {
    keyPath: ['Details', 'City'],
    name: 'City',
    displayName: 'City',
    type: ColumnType.String,
    pii: true,
    phi: false,
    otherField: true,
    required: false,
    custom: true,
    updatable: false,
  }, {
    keyPath: ['Details', 'ConditionState'],
    name: 'ConditionState',
    displayName: 'Condition State',
    type: ColumnType.String,
    pii: true,
    phi: true,
    required: false,
    custom: true,
    updatable: false,
  }, {
    keyPath: ['Details', 'Conditions'],
    name: 'Conditions',
    displayName: 'Conditions',
    type: ColumnType.String,
    pii: true,
    phi: true,
    required: false,
    custom: true,
    updatable: false,
  }, {
    keyPath: ['Details', 'Confirmed'],
    name: 'Confirmed',
    displayName: 'Confirmed',
    type: ColumnType.Number,
    pii: false,
    phi: false,
    required: false,
    custom: true,
    updatable: false,
  }, {
    keyPath: ['Details', 'Exposures'],
    name: 'Exposures',
    displayName: 'Exposures',
    type: ColumnType.String,
    pii: true,
    phi: true,
    required: false,
    custom: true,
    updatable: false,
  }, {
    keyPath: ['Details', 'Installation'],
    name: 'Installation',
    displayName: 'Installation',
    type: ColumnType.String,
    pii: true,
    phi: false,
    otherField: true,
    required: false,
    custom: true,
    updatable: false,
  }, {
    keyPath: ['Details', 'Location'],
    name: 'Location',
    displayName: 'Location',
    type: ColumnType.String,
    pii: true,
    phi: false,
    otherField: true,
    required: false,
    custom: true,
    updatable: false,
  }, {
    keyPath: ['Details', 'Lodging'],
    name: 'Lodging',
    displayName: 'Lodging',
    type: ColumnType.String,
    pii: true,
    phi: false,
    otherField: true,
    required: false,
    custom: true,
    updatable: false,
  }, {
    keyPath: ['Details', 'Medications'],
    name: 'Medications',
    displayName: 'Medications',
    type: ColumnType.String,
    pii: true,
    phi: true,
    required: false,
    custom: true,
    updatable: false,
  }, {
    keyPath: ['Details', 'PhoneNumber'],
    name: 'PhoneNumber',
    displayName: 'Phone Number',
    type: ColumnType.String,
    pii: true,
    phi: false,
    required: false,
    custom: true,
    updatable: false,
  }, {
    keyPath: ['Details', 'ROM'],
    name: 'ROM',
    displayName: 'ROM',
    type: ColumnType.Number,
    pii: false,
    phi: false,
    required: false,
    custom: true,
    updatable: false,
  }, {
    keyPath: ['Details', 'ROMContact'],
    name: 'ROMContact',
    displayName: 'ROM Contact',
    type: ColumnType.String,
    pii: true,
    phi: false,
    required: false,
    custom: true,
    updatable: false,
  }, {
    keyPath: ['Details', 'ROMStartDate'],
    name: 'ROMStartDate',
    displayName: 'ROM Start Date',
    type: ColumnType.String,
    pii: false,
    phi: false,
    required: false,
    custom: true,
    updatable: false,
  }, {
    keyPath: ['Details', 'ROMSupport'],
    name: 'ROMSupport',
    displayName: 'ROM Support',
    type: ColumnType.Number,
    pii: false,
    phi: false,
    required: false,
    custom: true,
    updatable: false,
  }, {
    keyPath: ['Details', 'RoomNumber'],
    name: 'RoomNumber',
    displayName: 'Room Number',
    type: ColumnType.String,
    pii: true,
    phi: false,
    required: false,
    custom: true,
    updatable: false,
  }, {
    keyPath: ['Details', 'Ship'],
    name: 'Ship',
    displayName: 'Ship',
    type: ColumnType.String,
    pii: true,
    phi: false,
    otherField: true,
    required: false,
    custom: true,
    updatable: false,
  }, {
    keyPath: ['Details', 'SpO2Percent'],
    name: 'Sp02Percent',
    displayName: 'Sp02 Percent',
    type: ColumnType.Number,
    pii: true,
    phi: true,
    required: false,
    custom: true,
    updatable: false,
  }, {
    keyPath: ['Details', 'Symptoms'],
    name: 'Symptoms',
    displayName: 'Symptoms',
    type: ColumnType.String,
    pii: true,
    phi: true,
    required: false,
    custom: true,
    updatable: false,
  }, {
    keyPath: ['Details', 'TalkToSomeone'],
    name: 'TalkToSomeone',
    displayName: 'Talk To Someone',
    type: ColumnType.Number,
    pii: true,
    phi: true,
    required: false,
    custom: true,
    updatable: false,
  }, {
    keyPath: ['Details', 'TemperatureFahrenheit'],
    name: 'TemperatureFahrenheit',
    displayName: 'Temperature Fahrenheit',
    type: ColumnType.Number,
    pii: true,
    phi: true,
    required: false,
    custom: true,
    updatable: false,
  }, {
    keyPath: ['Details', 'TentOrBillet'],
    name: 'TentOrBillet',
    displayName: 'Tent Or Billet',
    type: ColumnType.String,
    pii: true,
    phi: false,
    required: false,
    custom: true,
    updatable: false,
  }, {
    keyPath: ['Details', 'Unit'],
    name: 'Unit',
    displayName: 'Reported Unit',
    type: ColumnType.String,
    pii: true,
    phi: false,
    otherField: true,
    required: false,
    custom: true,
    updatable: false,
  }],
};

const oldDefaultReportSchema = {
  id: 'es6ddssymptomobs',
  columns: [{
    keyPath: ['Category'],
    name: 'Category',
    displayName: 'Category',
    type: ColumnType.String,
    pii: true,
    phi: true,
    required: false,
    custom: true,
    updatable: false,
  }, {
    keyPath: ['Score'],
    name: 'Score',
    displayName: 'Score',
    type: ColumnType.Number,
    pii: true,
    phi: true,
    required: false,
    custom: true,
    updatable: false,
  }, {
    keyPath: ['Details', 'Affiliation'],
    name: 'Affiliation',
    displayName: 'Affiliation',
    type: ColumnType.String,
    pii: false,
    phi: false,
    otherField: true,
    required: false,
    custom: true,
    updatable: false,
  }, {
    keyPath: ['Details', 'City'],
    name: 'City',
    displayName: 'City',
    type: ColumnType.String,
    pii: true,
    phi: false,
    otherField: true,
    required: false,
    custom: true,
    updatable: false,
  }, {
    keyPath: ['Details', 'ConditionState'],
    name: 'ConditionState',
    displayName: 'Condition State',
    type: ColumnType.String,
    pii: true,
    phi: true,
    required: false,
    custom: true,
    updatable: false,
  }, {
    keyPath: ['Details', 'Conditions'],
    name: 'Conditions',
    displayName: 'Conditions',
    type: ColumnType.String,
    pii: true,
    phi: true,
    required: false,
    custom: true,
    updatable: false,
  }, {
    keyPath: ['Details', 'Confirmed'],
    name: 'Confirmed',
    displayName: 'Confirmed',
    type: ColumnType.Number,
    pii: false,
    phi: false,
    required: false,
    custom: true,
    updatable: false,
  }, {
    keyPath: ['Details', 'Exposures'],
    name: 'Exposures',
    displayName: 'Exposures',
    type: ColumnType.String,
    pii: true,
    phi: true,
    required: false,
    custom: true,
    updatable: false,
  }, {
    keyPath: ['Details', 'Installation'],
    name: 'Installation',
    displayName: 'Installation',
    type: ColumnType.String,
    pii: true,
    phi: false,
    otherField: true,
    required: false,
    custom: true,
    updatable: false,
  }, {
    keyPath: ['Details', 'Location'],
    name: 'Location',
    displayName: 'Location',
    type: ColumnType.String,
    pii: true,
    phi: false,
    otherField: true,
    required: false,
    custom: true,
    updatable: false,
  }, {
    keyPath: ['Details', 'Lodging'],
    name: 'Lodging',
    displayName: 'Lodging',
    type: ColumnType.String,
    pii: true,
    phi: false,
    otherField: true,
    required: false,
    custom: true,
    updatable: false,
  }, {
    keyPath: ['Details', 'Medications'],
    name: 'Medications',
    displayName: 'Medications',
    type: ColumnType.String,
    pii: true,
    phi: true,
    required: false,
    custom: true,
    updatable: false,
  }, {
    keyPath: ['Details', 'PhoneNumber'],
    name: 'PhoneNumber',
    displayName: 'Phone Number',
    type: ColumnType.String,
    pii: true,
    phi: false,
    required: false,
    custom: true,
    updatable: false,
  }, {
    keyPath: ['Details', 'ROM'],
    name: 'ROM',
    displayName: 'ROM',
    type: ColumnType.Number,
    pii: false,
    phi: false,
    required: false,
    custom: true,
    updatable: false,
  }, {
    keyPath: ['Details', 'ROMContact'],
    name: 'ROMContact',
    displayName: 'ROM Contact',
    type: ColumnType.String,
    pii: true,
    phi: false,
    required: false,
    custom: true,
    updatable: false,
  }, {
    keyPath: ['Details', 'ROMStartDate'],
    name: 'ROMStartDate',
    displayName: 'ROM Start Date',
    type: ColumnType.String,
    pii: false,
    phi: false,
    required: false,
    custom: true,
    updatable: false,
  }, {
    keyPath: ['Details', 'ROMSupport'],
    name: 'ROMSupport',
    displayName: 'ROM Support',
    type: ColumnType.Number,
    pii: false,
    phi: false,
    required: false,
    custom: true,
    updatable: false,
  }, {
    keyPath: ['Details', 'RoomNumber'],
    name: 'RoomNumber',
    displayName: 'Room Number',
    type: ColumnType.String,
    pii: true,
    phi: false,
    required: false,
    custom: true,
    updatable: false,
  }, {
    keyPath: ['Details', 'Ship'],
    name: 'Ship',
    displayName: 'Ship',
    type: ColumnType.String,
    pii: true,
    phi: false,
    otherField: true,
    required: false,
    custom: true,
    updatable: false,
  }, {
    keyPath: ['Details', 'SpO2Percent'],
    name: 'Sp02Percent',
    displayName: 'Sp02 Percent',
    type: ColumnType.Number,
    pii: true,
    phi: true,
    required: false,
    custom: true,
    updatable: false,
  }, {
    keyPath: ['Details', 'Symptoms'],
    name: 'Symptoms',
    displayName: 'Symptoms',
    type: ColumnType.String,
    pii: true,
    phi: true,
    required: false,
    custom: true,
    updatable: false,
  }, {
    keyPath: ['Details', 'TalkToSomeone'],
    name: 'TalkToSomeone',
    displayName: 'Talk To Someone',
    type: ColumnType.Number,
    pii: true,
    phi: true,
    required: false,
    custom: true,
    updatable: false,
  }, {
    keyPath: ['Details', 'TemperatureFahrenheit'],
    name: 'TemperatureFahrenheit',
    displayName: 'Temperature Fahrenheit',
    type: ColumnType.Number,
    pii: true,
    phi: true,
    required: false,
    custom: true,
    updatable: false,
  }, {
    keyPath: ['Details', 'TentOrBillet'],
    name: 'TentOrBillet',
    displayName: 'Tent Or Billet',
    type: ColumnType.String,
    pii: true,
    phi: false,
    required: false,
    custom: true,
    updatable: false,
  }, {
    keyPath: ['Details', 'Unit'],
    name: 'Unit',
    displayName: 'Unit',
    type: ColumnType.String,
    pii: true,
    phi: false,
    otherField: true,
    required: false,
    custom: true,
    updatable: false,
  }],
};
